import { useEffect, useMemo, useState } from 'preact/hooks';
import { ResultMetric, shareResult } from '../../../components/tools/CalculatorUi';
import { breedingRankMeta } from '../../../data/palworld/breeding-ranks';
import { palsById, regularBreedingPals } from '../../../data/palworld/pals';
import { calculateBreeding } from './calculate';
import { PalPicker } from '../ui';

export default function Calculator() {
  const [parentAId, setParentAId] = useState(regularBreedingPals.find((pal) => pal.name === 'Lamball')?.id ?? regularBreedingPals[0].id);
  const [parentBId, setParentBId] = useState(regularBreedingPals.find((pal) => pal.name === 'Cattiva')?.id ?? regularBreedingPals[1].id);
  useEffect(() => { const params = new URLSearchParams(location.search); const parentA = params.get('parentA'); const parentB = params.get('parentB'); if (parentA && palsById.has(parentA)) setParentAId(parentA); if (parentB && palsById.has(parentB)) setParentBId(parentB); }, []);
  const parentA = palsById.get(parentAId) ?? regularBreedingPals[0]; const parentB = palsById.get(parentBId) ?? regularBreedingPals[1]; const result = useMemo(() => calculateBreeding(parentA, parentB), [parentA, parentB]);
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Special overrides before rank matching</span><h2>Find the child from two parent Pals</h2></div><button class="text-button" type="button" onClick={() => { setParentAId(parentBId); setParentBId(parentAId); }}>Swap parents</button></div><div class="comparison-picker-grid"><PalPicker label="Parent A" value={parentAId} onChange={setParentAId}/><span aria-hidden="true">＋</span><PalPicker label="Parent B" value={parentBId} onChange={setParentBId}/></div><div class="primary-result"><span>Expected child</span><strong>{result.child?.name ?? 'No eligible child'}</strong><p>{result.special ? 'Reviewed special combination overrides normal rank matching' : `Nearest eligible Pal to calculated rank ${result.targetRank}`}</p></div><div class="secondary-result-grid"><ResultMetric label="Child breeding rank" value={result.child?.breedingPower ?? '—'}/><ResultMetric label="Parent A rank" value={parentA.breedingPower}/><ResultMetric label="Parent B rank" value={parentB.breedingPower}/><ResultMetric label="Calculated target rank" value={result.targetRank}/><ResultMetric label="Special combination" value={result.special ? 'Yes' : 'No'} tone={result.special ? 'good' : 'default'}/></div><details class="advanced-settings" open><summary>Breeding decision path <span>+</span></summary><div class="formula-breakdown"><p>First, the local special-combination table is checked in either parent order.</p><p>If no override exists: floor(({parentA.breedingPower} + {parentB.breedingPower} + 1) ÷ 2) = {result.targetRank}. The closest regular-eligible breeding rank wins; stable game-data order resolves an equal-distance tie.</p></div></details><div class="calculator-actions"><button class="button button--primary" type="button" onClick={() => shareResult('Palworld breeding result', `${parentA.name} + ${parentB.name} → ${result.child?.name ?? 'no result'}${result.special ? ' (special combination)' : ` (target rank ${result.targetRank})`}.`)}>Share result</button></div><p class="assumption-note"><a href={breedingRankMeta.sourceUrl} target="_blank" rel="noreferrer">{breedingRankMeta.source}</a> · reviewed {breedingRankMeta.reviewed}. Gender-restricted records and patch changes should be confirmed before committing a long Cake queue.</p></div>;
}
