import { useMemo, useState } from 'preact/hooks';
import { Field, ResultMetric, Segmented } from '../../components/tools/CalculatorUi';
import { defaultNatureRunePrice, osrsPriceMeta, osrsPriceRecords } from '../../data/osrs/alch-values';
import { osrsDropMeta, osrsDropPresets } from '../../data/osrs/drop-rates';
import { equipmentSlots, osrsEquipment } from '../../data/osrs/equipment';
import { osrsSkills } from '../../data/osrs/skills';
import { methodsForSkill } from '../../data/osrs/training-methods';
import { osrsXpMeta, xpForLevel } from '../../data/osrs/xp';
import { calculateAlch, calculateCombatLevel, calculateDropProbability, calculateMaxHit, calculateSkillPlan, calculateToaUniqueChance, calculateXpProgress, nextCombatIncrease, totalEquipment, type CombatLevels, type CombatStyle } from './calculate';
import DpsCalculator from './dps-calculator/Calculator';

type Props = { toolSlug: string; toolName: string };
const fmt = (value: number, digits = 0) => Number.isFinite(value) ? value.toLocaleString(undefined, { maximumFractionDigits: digits }) : '—';
const specificSkills: Record<string, string> = { 'woodcutting-calculator': 'Woodcutting', 'mining-calculator': 'Mining', 'construction-calculator': 'Construction', 'slayer-calculator': 'Slayer', 'zmi-calculator': 'Runecraft', 'smithing-calculator': 'Smithing', 'agility-calculator': 'Agility' };

function SkillCalculator({ fixedSkill }: { fixedSkill?: string }) {
  const [skill, setSkill] = useState(fixedSkill ?? 'Woodcutting'); const activeSkill = fixedSkill ?? skill; const methods = methodsForSkill(activeSkill); const [methodId, setMethodId] = useState(methods[0]?.id ?? 'woodcutting-oak'); const method = methods.find((item) => item.id === methodId) ?? methods[0];
  const [currentLevel, setCurrentLevel] = useState(50); const [targetLevel, setTargetLevel] = useState(70); const [currentXp, setCurrentXp] = useState(xpForLevel(50)); const [xpPerAction, setXpPerAction] = useState(method?.xpPerAction ?? 1); const [actionsPerHour, setActionsPerHour] = useState(method?.actionsPerHour ?? 0);
  const chooseSkill = (value: string) => { setSkill(value); const next = methodsForSkill(value)[0]; if (next) { setMethodId(next.id); setXpPerAction(next.xpPerAction); setActionsPerHour(next.actionsPerHour ?? 0); } };
  const chooseMethod = (value: string) => { setMethodId(value); const next = methods.find((item) => item.id === value); if (next) { setXpPerAction(next.xpPerAction); setActionsPerHour(next.actionsPerHour ?? 0); } };
  const safeMethod = method ?? { id: 'custom', skill: activeSkill, name: 'Custom method', xpPerAction, actionsPerHour, levelRequired: 1, source: 'User input', sourceUrl: osrsXpMeta.sourceUrl, reviewed: '2026-09-05', note: 'Enter reviewed XP per action.' };
  const result = calculateSkillPlan({ currentXp, targetLevel, method: safeMethod, xpPerActionOverride: xpPerAction, actionsPerHour });
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Exact XP table and action planner</span><h2>{fixedSkill ? `Plan ${fixedSkill} training` : 'Plan any OSRS skill target'}</h2></div><span class="reference-count">{activeSkill}</span></div><div class="secondary-input-grid">{!fixedSkill && <Field label="Skill"><select value={skill} onChange={(event) => chooseSkill((event.currentTarget as HTMLSelectElement).value)}>{osrsSkills.map((item) => <option value={item}>{item}</option>)}</select></Field>}<Field label="Current level"><input type="number" min="1" max="99" value={currentLevel} onInput={(event) => { const value = Number((event.currentTarget as HTMLInputElement).value); setCurrentLevel(value); setCurrentXp(xpForLevel(value)); }}/></Field><Field label="Current total XP"><input type="number" min="0" max="200000000" value={currentXp} onInput={(event) => setCurrentXp(Number((event.currentTarget as HTMLInputElement).value))}/></Field><Field label="Target level"><input type="number" min={currentLevel} max="99" value={targetLevel} onInput={(event) => setTargetLevel(Number((event.currentTarget as HTMLInputElement).value))}/></Field><Field label="Training method"><select value={safeMethod.id} onChange={(event) => chooseMethod((event.currentTarget as HTMLSelectElement).value)}>{methods.map((item) => <option value={item.id}>{item.name} · {item.xpPerAction} XP</option>)}</select></Field><Field label="XP per action override"><input type="number" min="0.01" step="0.1" value={xpPerAction} onInput={(event) => setXpPerAction(Number((event.currentTarget as HTMLInputElement).value))}/></Field><Field label="Actions per hour"><input type="number" min="0" value={actionsPerHour} onInput={(event) => setActionsPerHour(Number((event.currentTarget as HTMLInputElement).value))}/></Field></div><div class="primary-result"><span>Actions required</span><strong>{fmt(result.actions)} <small>{safeMethod.name}</small></strong><p>{fmt(result.xpRemaining)} XP from level {result.currentLevel} toward level {targetLevel}</p></div><div class="secondary-result-grid"><ResultMetric label="Current XP" value={fmt(result.currentXp)}/><ResultMetric label="Target XP" value={fmt(result.targetXp)}/><ResultMetric label="XP remaining" value={fmt(result.xpRemaining)}/><ResultMetric label="Estimated time" value={result.hours === null ? 'Enter rate' : `${fmt(result.hours, 1)} hr`}/><ResultMetric label="Percentage complete" value={`${result.percentComplete.toFixed(2)}%`}/><ResultMetric label="Method requirement" value={`Level ${safeMethod.levelRequired}`}/></div><p class="assumption-note"><a href={safeMethod.sourceUrl} target="_blank" rel="noreferrer">{safeMethod.source}: {safeMethod.name}</a> · reviewed {safeMethod.reviewed}. {safeMethod.note} XP per action and actions/hour remain editable for boosts, failures, banking, tick methods, and route differences.</p></div>;
}

function XpCalculator() {
  const [mode, setMode] = useState<'total' | 'within'>('total'); const [currentLevel, setCurrentLevel] = useState(1); const [enteredXp, setEnteredXp] = useState(0); const [target, setTarget] = useState(99); const totalXp = mode === 'total' ? enteredXp : xpForLevel(currentLevel) + enteredXp; const result = calculateXpProgress(totalXp, Math.max(currentLevel, target));
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Fast universal XP engine</span><h2>Convert OSRS XP and levels</h2></div><span class="reference-count">Detected level {result.currentLevel}</span></div><Segmented label="XP input" value={mode} options={[{ value: 'total', label: 'Total XP' }, { value: 'within', label: 'XP within current level' }]} onChange={setMode}/><div class="secondary-input-grid">{mode === 'within' && <Field label="Current level"><input type="number" min="1" max="99" value={currentLevel} onInput={(event) => setCurrentLevel(Number((event.currentTarget as HTMLInputElement).value))}/></Field>}<Field label={mode === 'total' ? 'Total XP' : 'XP earned within level'}><input type="number" min="0" max="200000000" value={enteredXp} onInput={(event) => setEnteredXp(Number((event.currentTarget as HTMLInputElement).value))}/></Field><Field label="Target level"><input type="number" min="1" max="99" value={target} onInput={(event) => setTarget(Number((event.currentTarget as HTMLInputElement).value))}/></Field></div><div class="primary-result"><span>XP remaining</span><strong>{fmt(result.xpRemaining)} <small>XP</small></strong><div class="progress-track"><i style={{ width: `${result.percentToTarget}%` }}></i></div><p>Current level {result.currentLevel} · target {result.targetLevel}</p></div><div class="secondary-result-grid"><ResultMetric label="Total current XP" value={fmt(result.currentXp)}/><ResultMetric label="Target XP" value={fmt(result.targetXp)}/><ResultMetric label="Current-level progress" value={`${result.currentLevelProgress.toFixed(2)}%`}/><ResultMetric label="Target progress" value={`${result.percentToTarget.toFixed(2)}%`}/></div><p class="assumption-note"><a href={osrsXpMeta.sourceUrl} target="_blank" rel="noreferrer">{osrsXpMeta.source}</a> · reviewed {osrsXpMeta.reviewed}. Level 99 is exactly 13,034,431 XP; the reverse lookup uses the same integer table.</p></div>;
}

function CombatLevelCalculator() {
  const [levels, setLevels] = useState<CombatLevels>({ attack: 70, strength: 70, defence: 70, hitpoints: 70, ranged: 70, magic: 70, prayer: 43 }); const result = calculateCombatLevel(levels); const next = nextCombatIncrease(levels);
  const fields = Object.keys(levels) as (keyof CombatLevels)[];
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Exact account combat formula</span><h2>Calculate an OSRS combat level</h2></div></div><div class="secondary-input-grid">{fields.map((key) => <Field label={key[0].toUpperCase() + key.slice(1)}><input type="number" min="1" max="99" value={levels[key]} onInput={(event) => setLevels({ ...levels, [key]: Number((event.currentTarget as HTMLInputElement).value) })}/></Field>)}</div><div class="primary-result"><span>Combat Level</span><strong>{result.combatLevel}</strong><p>{result.determiningStyle} currently supplies the largest offensive contribution</p></div><div class="secondary-result-grid"><ResultMetric label="Base combat" value={result.base.toFixed(3)}/><ResultMetric label="Melee contribution" value={result.melee.toFixed(3)}/><ResultMetric label="Ranged contribution" value={result.ranged.toFixed(3)}/><ResultMetric label="Magic contribution" value={result.magic.toFixed(3)}/><ResultMetric label="Next likely increase" value={next ? `+${next.levels} ${next.stat}` : 'Maxed'}/></div><details class="advanced-settings" open><summary>Combat formula <span>+</span></summary><div class="formula-breakdown"><p>Base = 0.25 × (Defence + Hitpoints + floor(Prayer ÷ 2)).</p><p>Final combat = floor(Base + max(0.325 × (Attack + Strength), 0.325 × floor(1.5 × Ranged), 0.325 × floor(1.5 × Magic))).</p></div></details></div>;
}

function DropRateCalculator() {
  const [rate, setRate] = useState('1/512'); const [kills, setKills] = useState(512); const result = calculateDropProbability(rate, kills);
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Independent-drop probability</span><h2>See dry chance and reverse kill targets</h2></div></div><div class="secondary-input-grid"><Field label="Drop rate"><input value={rate} placeholder="1/512" onInput={(event) => setRate((event.currentTarget as HTMLInputElement).value)}/></Field><Field label="Number of kills"><input type="number" min="0" value={kills} onInput={(event) => setKills(Number((event.currentTarget as HTMLInputElement).value))}/></Field><Field label="Known OSRS preset"><select value="" onChange={(event) => { const preset = osrsDropPresets.find((item) => item.id === (event.currentTarget as HTMLSelectElement).value); if (preset) setRate(`1/${preset.denominator}`); }}><option value="">Choose a drop</option>{osrsDropPresets.map((item) => <option value={item.id}>{item.name} · 1/{item.denominator}</option>)}</select></Field></div><div class="primary-result"><span>Chance of at least one drop</span><strong>{(result.atLeastOne * 100).toFixed(4)}<small>%</small></strong><div class="progress-track"><i style={{ width: `${result.atLeastOne * 100}%` }}></i></div><p>{(result.zeroChance * 100).toFixed(4)}% chance of receiving zero in {fmt(kills)} kills</p></div><div class="secondary-result-grid"><ResultMetric label="Expected drops" value={result.expectedDrops.toFixed(3)}/><ResultMetric label="Expected kills for one" value={fmt(result.expectedKills, 1)}/>{result.milestones.map((row) => <ResultMetric label={`${row.target * 100}% chance`} value={fmt(row.kills)} suffix=" kills"/>)}</div><p class="assumption-note"><a href={osrsDropMeta.sourceUrl} target="_blank" rel="noreferrer">{osrsDropMeta.source}</a> · reviewed {osrsDropMeta.reviewed}. Probability is 1 − (1 − p)ⁿ. Independent drops have no memory unless Jagex documents a separate pity or threshold mechanic.</p></div>;
}

function AlchCalculator() {
  const defaultItem = osrsPriceRecords.find((item) => item.name === 'Rune platebody') ?? osrsPriceRecords[0]; const [query, setQuery] = useState('Rune platebody'); const matches = useMemo(() => osrsPriceRecords.filter((item) => item.name.toLowerCase().includes(query.toLowerCase())).slice(0, 50), [query]); const [itemId, setItemId] = useState(defaultItem.id); const [nature, setNature] = useState(defaultNatureRunePrice); const [quantity, setQuantity] = useState(100); const selected = osrsPriceRecords.find((item) => item.id === itemId) ?? matches[0] ?? defaultItem; const result = calculateAlch(selected, nature, quantity);
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Dated local Grand Exchange snapshot</span><h2>Calculate High Alchemy profit</h2></div><span class="reference-count">{fmt(osrsPriceRecords.length)} priced items</span></div><div class="secondary-input-grid"><Field label="Search item"><input type="search" value={query} onInput={(event) => setQuery((event.currentTarget as HTMLInputElement).value)}/></Field><Field label="Matching item"><select value={selected.id} onChange={(event) => setItemId(Number((event.currentTarget as HTMLSelectElement).value))}>{matches.map((item) => <option value={item.id}>{item.name}</option>)}</select></Field><Field label="Nature rune cost"><input type="number" min="0" value={nature} onInput={(event) => setNature(Number((event.currentTarget as HTMLInputElement).value))}/></Field><Field label="Quantity"><input type="number" min="1" max="100000" value={quantity} onInput={(event) => setQuantity(Number((event.currentTarget as HTMLInputElement).value))}/></Field></div><div class="primary-result"><span>Net profit / loss</span><strong>{result.totalProfit >= 0 ? '+' : ''}{fmt(result.totalProfit)} <small>coins</small></strong><p>{selected.name} · {fmt(result.netPerItem)} coins per cast after one Nature rune</p></div><div class="secondary-result-grid"><ResultMetric label="GE buy price" value={fmt(result.geBuyPrice)}/><ResultMetric label="High Alchemy value" value={fmt(result.highAlch)}/><ResultMetric label="Gross difference" value={fmt(result.grossPerItem)}/><ResultMetric label="Net per item" value={fmt(result.netPerItem)} tone={result.netPerItem >= 0 ? 'good' : 'bad'}/><ResultMetric label="Profit per 100" value={fmt(result.profitPer100)}/><ResultMetric label="Profit per 1,000" value={fmt(result.profitPer1000)}/></div><p class="assumption-note"><a href={osrsPriceMeta.sourceUrl} target="_blank" rel="noreferrer">{osrsPriceMeta.source}</a> · snapshot {new Date(osrsPriceMeta.snapshotTimestamp).toLocaleString()}. GE prices are community API observations copied into this static build; buy limits, spread, fees, and fills can change after the snapshot.</p></div>;
}

function MaxHitCalculator() {
  const [style, setStyle] = useState<CombatStyle>('melee'); const [level, setLevel] = useState(99); const [boost, setBoost] = useState(19); const [prayer, setPrayer] = useState(1.23); const [styleBonus, setStyleBonus] = useState(3); const [strengthBonus, setStrengthBonus] = useState(132); const [special, setSpecial] = useState(1); const [spellDamage, setSpellDamage] = useState(24); const result = calculateMaxHit({ style, level, boost, prayerMultiplier: prayer, styleBonus, strengthBonus, damageMultiplier: special, magicBaseDamage: spellDamage });
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Effective-level damage formula</span><h2>Inspect an OSRS maximum hit</h2></div></div><Segmented label="Combat style" value={style} options={[{ value: 'melee', label: 'Melee' }, { value: 'ranged', label: 'Ranged' }, { value: 'magic', label: 'Magic' }]} onChange={setStyle}/><div class="secondary-input-grid"><Field label="Skill level"><input type="number" min="1" max="99" value={level} onInput={(event) => setLevel(Number((event.currentTarget as HTMLInputElement).value))}/></Field><Field label="Visible boost"><input type="number" min="0" max="30" value={boost} onInput={(event) => setBoost(Number((event.currentTarget as HTMLInputElement).value))}/></Field>{style !== 'magic' && <><Field label="Prayer multiplier"><input type="number" min="1" max="1.3" step="0.01" value={prayer} onInput={(event) => setPrayer(Number((event.currentTarget as HTMLInputElement).value))}/></Field><Field label="Style bonus"><input type="number" min="0" max="3" value={styleBonus} onInput={(event) => setStyleBonus(Number((event.currentTarget as HTMLInputElement).value))}/></Field></>}{style === 'magic' && <Field label="Spell base damage"><input type="number" min="0" value={spellDamage} onInput={(event) => setSpellDamage(Number((event.currentTarget as HTMLInputElement).value))}/></Field>}<Field label={style === 'magic' ? 'Magic damage bonus' : 'Equipment strength bonus'} hint={style === 'magic' ? '%' : undefined}><input type="number" min="-100" max="500" value={strengthBonus} onInput={(event) => setStrengthBonus(Number((event.currentTarget as HTMLInputElement).value))}/></Field><Field label="Special modifier"><input type="number" min="0.1" max="5" step="0.05" value={special} onInput={(event) => setSpecial(Number((event.currentTarget as HTMLInputElement).value))}/></Field></div><div class="primary-result"><span>Final maximum hit</span><strong>{result.finalMaxHit}</strong><p>Base max {result.baseMaxHit} · applied modifier ×{result.appliedMultiplier}</p></div><div class="secondary-result-grid"><ResultMetric label="Effective level" value={result.effectiveLevel}/><ResultMetric label="Damage bonus" value={result.strengthBonus}/><ResultMetric label="Base max hit" value={result.baseMaxHit}/><ResultMetric label="Final max hit" value={result.finalMaxHit}/></div><p class="assumption-note"><a href="https://oldschool.runescape.wiki/w/Maximum_melee_hit" target="_blank" rel="noreferrer">OSRS Wiki maximum-hit formulas</a> · reviewed 2026-09-05. Special-attack and set multipliers are manual so the result never assumes an item effect that was not selected.</p></div>;
}

type Setup = Record<string, number>;
function GearCalculator() {
  const emptySetup = Object.fromEntries(equipmentSlots.map((slot) => [slot, osrsEquipment.find((item) => item.slot === slot)?.id ?? 0])); const [a, setA] = useState<Setup>(emptySetup); const [b, setB] = useState<Setup>(emptySetup);
  const items = (setup: Setup) => equipmentSlots.map((slot) => osrsEquipment.find((item) => item.id === setup[slot])!).filter(Boolean); const totalA = totalEquipment(items(a)); const totalB = totalEquipment(items(b)); const price = (setup: Setup) => items(setup).reduce((sum, item) => sum + (osrsPriceRecords.find((price) => price.name === item.name)?.highPrice ?? 0), 0);
  const editor = (label: string, setup: Setup, update: (value: Setup) => void) => <section class="gear-setup"><h3>{label}</h3>{equipmentSlots.map((slot) => <Field label={slot[0].toUpperCase() + slot.slice(1)}><select value={setup[slot]} onChange={(event) => update({ ...setup, [slot]: Number((event.currentTarget as HTMLSelectElement).value) })}>{osrsEquipment.filter((item) => item.slot === slot).map((item) => <option value={item.id}>{item.name}</option>)}</select></Field>)}</section>;
  const metrics = [['Slash attack', 'attackSlash'], ['Ranged attack', 'attackRanged'], ['Magic attack', 'attackMagic'], ['Melee strength', 'meleeStrength'], ['Ranged strength', 'rangedStrength'], ['Magic damage %', 'magicDamage'], ['Prayer', 'prayer']] as const;
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Eleven equipment slots</span><h2>Compare two OSRS gear setups</h2></div><button class="text-button" type="button" onClick={() => { setA(b); setB(a); }}>Swap</button></div><div class="gear-compare-grid">{editor('Setup A', a, setA)}{editor('Setup B', b, setB)}</div><div class="interactive-table-wrap"><table class="interactive-table"><thead><tr><th>Bonus</th><th>Setup A</th><th>Setup B</th><th>Difference A−B</th></tr></thead><tbody>{metrics.map(([label, key]) => <tr><th>{label}</th><td>{totalA[key]}</td><td>{totalB[key]}</td><td>{totalA[key] - totalB[key]}</td></tr>)}<tr><th>Approximate GE cost</th><td>{fmt(price(a))}</td><td>{fmt(price(b))}</td><td>{fmt(price(a) - price(b))}</td></tr></tbody></table></div><p class="assumption-note">Equipment bonuses come from reviewed OSRS Wiki item pages. Cost uses the same dated local Wiki price snapshot as High Alchemy and may be zero for untradeable or unmatched items. Set effects and charged-item state are not inferred.</p></div>;
}

function ToaCalculator() {
  const [raidLevel, setRaidLevel] = useState(400); const [points, setPoints] = useState(37_000); const [deaths, setDeaths] = useState(0); const pointsAfterDeaths = Array.from({ length: Math.max(0, Math.floor(deaths)) }).reduce((current) => Math.max(0, Number(current) - Math.max(1_000, Number(current) * 0.2)), points) as number; const result = calculateToaUniqueChance(raidLevel, Math.max(0, pointsAfterDeaths - 5_000));
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Tombs of Amascut reward model</span><h2>Estimate ToA unique chance from points</h2></div></div><div class="secondary-input-grid"><Field label="Raid level"><input type="number" min="0" max="700" value={raidLevel} onInput={(event) => setRaidLevel(Number((event.currentTarget as HTMLInputElement).value))}/></Field><Field label="Total reward points before final start-point subtraction"><input type="number" min="0" max="64000" value={points} onInput={(event) => setPoints(Number((event.currentTarget as HTMLInputElement).value))}/></Field><Field label="Player deaths"><input type="number" min="0" max="20" value={deaths} onInput={(event) => setDeaths(Number((event.currentTarget as HTMLInputElement).value))}/></Field></div><div class="primary-result"><span>Estimated party unique chance</span><strong>{result.chancePercent.toFixed(3)}<small>%</small></strong><p>{fmt(Math.max(0, pointsAfterDeaths - 5_000))} eligible reward points · {fmt(result.pointsPerPercent, 1)} points per 1%</p></div><div class="secondary-result-grid"><ResultMetric label="Scaled raid level" value={result.scaledRaidLevel.toFixed(2)}/><ResultMetric label="Points after deaths" value={fmt(pointsAfterDeaths)}/><ResultMetric label="Start points subtracted" value="5,000"/><ResultMetric label="55% cap reached" value={result.capped ? 'Yes' : 'No'}/></div><p class="assumption-note"><a href="https://oldschool.runescape.wiki/w/Chest_(Tombs_of_Amascut)" target="_blank" rel="noreferrer">OSRS Wiki ToA reward-point formula</a> · reviewed 2026-09-05. The group rolls only one unique; an individual’s allocation is proportional to contribution. Room scoring, MVP bonuses, path details, disconnects, and restricted-item 1/50 rerolls are outside these three inputs.</p></div>;
}

export default function Calculator({ toolSlug }: Props) {
  if (toolSlug === 'xp-calculator') return <XpCalculator/>;
  if (toolSlug === 'skill-calculator') return <SkillCalculator/>;
  if (specificSkills[toolSlug]) return <SkillCalculator fixedSkill={specificSkills[toolSlug]}/>;
  if (toolSlug === 'combat-level-calculator') return <CombatLevelCalculator/>;
  if (toolSlug === 'drop-rate-calculator') return <DropRateCalculator/>;
  if (toolSlug === 'alch-calculator') return <AlchCalculator/>;
  if (toolSlug === 'max-hit-calculator') return <MaxHitCalculator/>;
  if (toolSlug === 'gear-calculator') return <GearCalculator/>;
  if (toolSlug === 'dps-calculator') return <DpsCalculator/>;
  return <ToaCalculator/>;
}
