import {useEffect,useMemo,useRef,useState} from 'preact/hooks';import {Map as MapLibreMap,Marker,NavigationControl} from 'maplibre-gl';import 'maplibre-gl/dist/maplibre-gl.css';import {gtaMapLocations,type GtaMapLocation} from '../../../data/gta-6/map-locations';
type Category='all'|GtaMapLocation['category'];
export default function Calculator(){const container=useRef<HTMLDivElement>(null);const map=useRef<MapLibreMap>();const markers=useRef<Marker[]>([]);const[query,setQuery]=useState('');const[category,setCategory]=useState<Category>('all');const[selected,setSelected]=useState<GtaMapLocation|null>(null);const[visited,setVisited]=useState<Set<string>>(new Set());
  useEffect(()=>{const saved=JSON.parse(localStorage.getItem('gc:map:gta-6')??'[]') as string[];setVisited(new Set(saved));const id=new URLSearchParams(location.search).get('location');setSelected(gtaMapLocations.find((place)=>place.id===id)??null)},[]);
  useEffect(()=>{if(!container.current||map.current)return;const instance=new MapLibreMap({container:container.current,center:[-80.22,25.75],zoom:8.3,style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]}});map.current=instance;instance.addControl(new NavigationControl({showCompass:false}),'top-right');return()=>{instance.remove();map.current=undefined}},[]);
  const filtered=useMemo(()=>gtaMapLocations.filter((place)=>(category==='all'||place.category===category)&&place.name.toLowerCase().includes(query.toLowerCase())),[category,query]);
  useEffect(()=>{if(!map.current)return;markers.current.forEach((marker)=>marker.remove());markers.current=filtered.map((place)=>{const marker=new Marker({color:visited.has(place.id)?'#4ade80':'#fb7185'}).setLngLat(place.coordinates).addTo(map.current!);marker.getElement().setAttribute('aria-label',place.name);marker.getElement().addEventListener('click',()=>select(place));return marker})},[filtered,visited]);
  const select=(place:GtaMapLocation)=>{setSelected(place);map.current?.flyTo({center:place.coordinates,zoom:11});const params=new URLSearchParams(location.search);params.set('location',place.id);history.replaceState({},'',`${location.pathname}?${params}`)};
  const toggleVisited=()=>{if(!selected)return;const next=new Set(visited);next.has(selected.id)?next.delete(selected.id):next.add(selected.id);setVisited(next);localStorage.setItem('gc:map:gta-6',JSON.stringify([...next]))};
  return <div class="calculator map-calculator"><div class="calculator-header"><div><span class="eyebrow">Reusable map preview</span><h2>Explore sample locations</h2></div><span class="sample-badge">Sample data</span></div><div class="map-controls"><label><span class="sr-only">Search locations</span><input type="search" placeholder="Search locations" value={query} onInput={(e)=>setQuery((e.target as HTMLInputElement).value)}/></label><div>{(['all','city','nature','landmark'] as Category[]).map((item)=><button type="button" class={category===item?'active':''} onClick={()=>setCategory(item)}>{item}</button>)}</div></div><div class="map-layout"><div class="map-list">{filtered.map((place)=><button type="button" class={selected?.id===place.id?'active':''} onClick={()=>select(place)}><span class={visited.has(place.id)?'visited':''}>{visited.has(place.id)?'✓':'•'}</span><span><strong>{place.name}</strong><small>{place.category} · unverified sample</small></span></button>)}</div><div ref={container} class="map-canvas" aria-label="Interactive GTA VI sample location map"></div></div>{selected&&<div class="map-detail"><div><span class="eyebrow">{selected.category} · sample marker</span><h3>{selected.name}</h3><p>{selected.description}</p></div><div><button class="button button--primary" type="button" onClick={toggleVisited}>{visited.has(selected.id)?'✓ Visited':'Mark visited'}</button><button class="button button--secondary" type="button" onClick={()=>navigator.clipboard.writeText(location.href)}>Copy location link</button></div></div>}<p class="assumption-note">All markers are clearly labeled sample data. Verified locations can replace this local file after release without rebuilding the map component.</p></div>}
