import { useEffect, useMemo, useState } from 'preact/hooks';
import { Field, ResultMetric, Segmented } from '../../components/tools/CalculatorUi';
import { evolutionMeta, evolutionsFrom } from '../../data/pokemon-go/evolutions';
import { moveMeta, pokemonMovePools, pveChargedMoves, pveFastMoves, pvpChargedMoves, pvpFastMoves } from '../../data/pokemon-go/moves';
import { powerUpMeta } from '../../data/pokemon-go/power-up-costs';
import { pokemonSpeciesById } from '../../data/pokemon-go/species';
import { pokemonGoTradeRules, type FriendshipLevel, type TradePokemonClass } from '../../data/pokemon-go/trade-rules';
import { maxTrainerLevel, trainerXpByLevel, trainerXpMeta } from '../../data/pokemon-go/trainer-xp';
import type { PokemonMove } from '../../data/pokemon-go/types';
import { calculateEvolutionRange, calculateMoveDps, calculatePokemonStats, calculatePowerUpCost, calculatePvpRank, calculateTrade, calculateTrainerXp, purifyIvs, trainerLevelFromXp, type PokemonIvs } from './calculate';
import CpCalculator from './cp-calculator/Calculator';
import { formatStat, IvFields, LevelPicker, PokemonPicker } from './ui';

type Props = { toolSlug: string; toolName: string };
const perfect: PokemonIvs = { attack: 15, defense: 15, stamina: 15 };
const number = (value: number, digits = 0) => value.toLocaleString(undefined, { maximumFractionDigits: digits });
const speciesOrDefault = (id: string) => pokemonSpeciesById.get(id) ?? pokemonSpeciesById.get('1-normal')!;

function EvolutionCalculator() {
  const [mode, setMode] = useState<'exact' | 'quick'>('exact');
  const [speciesId, setSpeciesId] = useState('1-normal');
  const edges = evolutionsFrom(speciesId);
  const [targetId, setTargetId] = useState(edges[0]?.toId ?? '2-normal');
  const [level, setLevel] = useState(20);
  const [ivs, setIvs] = useState<PokemonIvs>(perfect);
  const [currentCpInput, setCurrentCpInput] = useState(637);
  useEffect(() => { const next = evolutionsFrom(speciesId)[0]; if (next) setTargetId(next.toId); }, [speciesId]);
  const current = speciesOrDefault(speciesId); const target = speciesOrDefault(targetId);
  const currentResult = useMemo(() => calculatePokemonStats(current, level, ivs), [current, level, ivs]);
  const targetResult = useMemo(() => calculatePokemonStats(target, level, ivs), [target, level, ivs]);
  const range = useMemo(() => mode === 'quick' ? calculateEvolutionRange(current, target, Math.max(10, currentCpInput)) : null, [mode, current, target, currentCpInput]);
  const edge = edges.find((item) => item.toId === targetId);
  if (!edges.length) return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Evolution CP prediction</span><h2>Choose a Pokémon that can evolve</h2></div></div><PokemonPicker value={speciesId} onChange={setSpeciesId} label="Current Pokémon"/><p class="assumption-note">The reviewed evolution table has no direct evolution from {current.name} in this form. Select an earlier member of an evolution family to calculate a target.</p><p class="assumption-note"><a href={evolutionMeta.sourceUrl} target="_blank" rel="noreferrer">{evolutionMeta.source}</a> · reviewed {evolutionMeta.reviewed}.</p></div>;
  return <div class="calculator universal-tool">
    <div class="calculator-header"><div><span class="eyebrow">Evolution CP prediction</span><h2>Compare current and evolved stats</h2></div></div>
    <Segmented label="Calculation mode" value={mode} options={[{ value: 'exact', label: 'Exact: level + IVs' }, { value: 'quick', label: 'Quick: current CP range' }]} onChange={setMode}/>
    <div class="secondary-input-grid"><PokemonPicker value={speciesId} onChange={setSpeciesId} label="Current Pokémon"/><Field label="Target evolution"><select value={targetId} onChange={(event) => setTargetId((event.currentTarget as HTMLSelectElement).value)}>{edges.map((item) => <option value={item.toId} key={item.toId}>{item.toName}{item.candyRequired ? ` · ${item.candyRequired} Candy` : ''}</option>)}</select></Field></div>
    {!edges.length && <p class="assumption-note">The reviewed evolution table has no direct evolution from this form. Choose another Pokémon.</p>}
    {mode === 'exact' ? <><div class="secondary-input-grid"><LevelPicker value={level} onChange={setLevel}/><IvFields ivs={ivs} setIvs={setIvs}/></div><div class="primary-result primary-result--blue"><span>Predicted evolved CP</span><strong>{targetResult.cp.toLocaleString()} <small>CP</small></strong><p>{currentResult.cp.toLocaleString()} → {targetResult.cp.toLocaleString()} CP · same level and IV spread</p></div><div class="secondary-result-grid"><ResultMetric label="Current CP" value={currentResult.cp}/><ResultMetric label="Predicted evolved HP" value={targetResult.hp}/><ResultMetric label="Current HP" value={currentResult.hp}/><ResultMetric label="CP difference" value={`+${number(targetResult.cp - currentResult.cp)}`}/><ResultMetric label="Evolution family" value={`${current.name} → ${target.name}`}/><ResultMetric label="Candy requirement" value={edge?.candyRequired ?? 'Condition varies'}/></div></> : <><Field label="Current CP"><input type="number" min="10" value={currentCpInput} onInput={(event) => setCurrentCpInput(Number((event.currentTarget as HTMLInputElement).value))}/></Field>{range && <><div class="primary-result primary-result--blue"><span>Possible evolved CP range</span><strong>{range.minimum.toLocaleString()}–{range.maximum.toLocaleString()} <small>CP</small></strong><p>{range.matches} closest level-and-IV combinations evaluated locally</p></div><p class="assumption-note">Quick mode cannot uniquely recover level and IVs from CP. The range uses the closest source-CP matches in the reviewed multiplier table; its source match is within {range.sourceCpTolerance} CP.</p></>}</>}
    <p class="assumption-note"><a href={evolutionMeta.sourceUrl} target="_blank" rel="noreferrer">{evolutionMeta.source}</a> · reviewed {evolutionMeta.reviewed}. Special requirements such as items, buddy tasks, time, gender, region, or walking distance are not replaced by the Candy field.</p>
  </div>;
}

function StatsCalculator() {
  const [speciesId, setSpeciesId] = useState('25-normal'); const [level, setLevel] = useState(30); const [ivs, setIvs] = useState<PokemonIvs>({ attack: 10, defense: 13, stamina: 12 });
  const species = speciesOrDefault(speciesId); const result = useMemo(() => calculatePokemonStats(species, level, ivs), [species, level, ivs]); const perfectResult = useMemo(() => calculatePokemonStats(species, level, perfect), [species, level]);
  const bars = [['Attack', result.effectiveAttack, perfectResult.effectiveAttack], ['Defense', result.effectiveDefense, perfectResult.effectiveDefense], ['Stamina', result.effectiveStamina, perfectResult.effectiveStamina]] as const;
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">CP, HP and effective stats</span><h2>Inspect a Pokémon’s stat profile</h2></div></div><div class="secondary-input-grid"><PokemonPicker value={speciesId} onChange={setSpeciesId}/><LevelPicker value={level} onChange={setLevel}/><IvFields ivs={ivs} setIvs={setIvs}/></div><div class="primary-result primary-result--blue"><span>Calculated stat product</span><strong>{number(result.statProduct)} <small>stat product</small></strong><p>{result.cp} CP · {result.hp} HP · {result.ivPercent.toFixed(1)}% IV</p></div><div class="secondary-result-grid"><ResultMetric label="CP" value={result.cp}/><ResultMetric label="HP" value={result.hp}/><ResultMetric label="Effective Attack" value={formatStat(result.effectiveAttack)}/><ResultMetric label="Effective Defense" value={formatStat(result.effectiveDefense)}/><ResultMetric label="Effective Stamina" value={formatStat(result.effectiveStamina)}/><ResultMetric label="IV percentage" value={`${result.ivPercent.toFixed(1)}%`}/></div><div class="stat-comparison">{bars.map(([label, currentValue, maxValue]) => <div key={label}><span><strong>{label}</strong><small>{formatStat(currentValue)} vs {formatStat(maxValue)} at 15 IV</small></span><i><b style={{ width: `${currentValue / maxValue * 100}%` }}></b></i></div>)}</div><p class="assumption-note">The 15/15/15 comparison holds species and level constant, so each bar isolates the selected IV spread instead of comparing different Pokémon.</p></div>;
}

function PvpCalculator() {
  const [speciesId, setSpeciesId] = useState('1-normal'); const [ivs, setIvs] = useState<PokemonIvs>({ attack: 0, defense: 15, stamina: 15 }); const [league, setLeague] = useState<'great' | 'ultra' | 'master' | 'custom'>('great'); const [customCap, setCustomCap] = useState(1000);
  const species = speciesOrDefault(speciesId); const cap = league === 'great' ? 1500 : league === 'ultra' ? 2500 : league === 'master' ? Infinity : Math.max(10, customCap); const result = useMemo(() => calculatePvpRank(species, ivs, cap), [species, ivs, cap]);
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">League stat-product rank</span><h2>Find the best eligible level</h2></div><span class="reference-count">Rank #{result.rank}</span></div><div class="secondary-input-grid"><PokemonPicker value={speciesId} onChange={setSpeciesId}/><Field label="League"><select value={league} onChange={(event) => setLeague((event.currentTarget as HTMLSelectElement).value as typeof league)}><option value="great">Great League · 1,500 CP</option><option value="ultra">Ultra League · 2,500 CP</option><option value="master">Master League · no CP cap</option><option value="custom">Custom CP cap</option></select></Field>{league === 'custom' && <Field label="Custom CP cap"><input type="number" min="10" max="10000" value={customCap} onInput={(event) => setCustomCap(Number((event.currentTarget as HTMLInputElement).value))}/></Field>}<IvFields ivs={ivs} setIvs={setIvs}/></div><div class="primary-result primary-result--blue"><span>Best eligible result</span><strong>{result.cp.toLocaleString()} <small>CP at level {result.level}</small></strong><p>Rank #{result.rank} · {result.rankPercent.toFixed(2)}% of rank #1 stat product</p></div><div class="secondary-result-grid"><ResultMetric label="Effective Attack" value={formatStat(result.effectiveAttack)}/><ResultMetric label="Effective Defense" value={formatStat(result.effectiveDefense)}/><ResultMetric label="Effective Stamina" value={formatStat(result.effectiveStamina)}/><ResultMetric label="Stat Product" value={number(result.statProduct)}/><ResultMetric label="Rank #1 IVs" value={`${result.best.ivs.attack}/${result.best.ivs.defense}/${result.best.ivs.stamina}`}/><ResultMetric label="Rank #1 level" value={result.best.level}/></div><p class="assumption-note">The browser evaluates all 4,096 IV spreads against the selected cap, caches the ranked table, and orders them by effective Attack × effective Defense × floored HP. It does not model breakpoints, moves, Best Buddy boosts, or limited-format eligibility.</p></div>;
}

function PurifyCalculator() {
  const [speciesId, setSpeciesId] = useState('1-normal'); const [ivs, setIvs] = useState<PokemonIvs>({ attack: 10, defense: 13, stamina: 12 }); const purified = purifyIvs(ivs); const percent = (purified.attack + purified.defense + purified.stamina) / 45 * 100;
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Verified IV change only</span><h2>Preview purified IVs</h2></div></div><div class="secondary-input-grid"><PokemonPicker value={speciesId} onChange={setSpeciesId}/><IvFields ivs={ivs} setIvs={setIvs}/></div><div class="primary-result primary-result--blue"><span>Purified IV spread</span><strong>{purified.attack} / {purified.defense} / {purified.stamina}</strong><p>{percent.toFixed(1)}% IV after adding two to each stat, capped at 15</p></div><div class="secondary-result-grid">{(['attack', 'defense', 'stamina'] as const).map((key) => <ResultMetric key={key} label={`${key[0].toUpperCase()}${key.slice(1)} becomes 15`} value={purified[key] === 15 ? 'Yes' : 'No'} tone={purified[key] === 15 ? 'good' : 'default'}/>)}</div><p class="assumption-note">This result applies only the deterministic +2 IV purification rule. Shadow damage bonuses, Stardust/Candy discounts, move changes, purification level, and battle value are separate mechanics and are not folded into the IV percentage.</p></div>;
}

function PowerUpCalculator() {
  const [speciesId, setSpeciesId] = useState('25-normal'); const [currentLevel, setCurrentLevel] = useState(20); const [targetLevel, setTargetLevel] = useState(40); const [ivs, setIvs] = useState<PokemonIvs>(perfect); const species = speciesOrDefault(speciesId);
  const safeTarget = Math.max(currentLevel, targetLevel); const current = calculatePokemonStats(species, currentLevel, ivs); const target = calculatePokemonStats(species, safeTarget, ivs); const costs = calculatePowerUpCost(currentLevel, safeTarget);
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Stardust, Candy and CP</span><h2>Plan a complete power-up path</h2></div></div><div class="secondary-input-grid"><PokemonPicker value={speciesId} onChange={setSpeciesId}/><LevelPicker value={currentLevel} onChange={(value) => { setCurrentLevel(value); if (targetLevel < value) setTargetLevel(value); }} label="Current level" maximum={49.5}/><LevelPicker value={targetLevel} onChange={setTargetLevel} label="Target level" minimum={currentLevel}/><IvFields ivs={ivs} setIvs={setIvs}/></div><div class="primary-result primary-result--blue"><span>Target CP</span><strong>{target.cp.toLocaleString()} <small>CP</small></strong><p>Gain {number(target.cp - current.cp)} CP across {costs.powerUps} half-level power-ups</p></div><div class="secondary-result-grid"><ResultMetric label="Current CP" value={current.cp}/><ResultMetric label="Target CP" value={target.cp}/><ResultMetric label="Stardust required" value={number(costs.stardust)}/><ResultMetric label="Candy required" value={number(costs.candy)}/><ResultMetric label="Candy XL required" value={number(costs.candyXl)}/><ResultMetric label="Number of power-ups" value={costs.powerUps}/></div><p class="assumption-note"><a href={powerUpMeta.sourceUrl} target="_blank" rel="noreferrer">{powerUpMeta.source}</a> · reviewed {powerUpMeta.reviewed}. Costs are for a normal Pokémon; Shadow and Purified cost multipliers are not silently applied.</p></div>;
}

function TradeCalculator() {
  const [friendship, setFriendship] = useState<FriendshipLevel>('ultra'); const [pokemonClass, setPokemonClass] = useState<TradePokemonClass>('standard-registered'); const [distance, setDistance] = useState(0); const result = calculateTrade(friendship, pokemonClass, Math.max(0, distance));
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Stardust and distance rules</span><h2>Check a Pokémon GO trade</h2></div></div><div class="secondary-input-grid"><Field label="Friendship level"><select value={friendship} onChange={(event) => setFriendship((event.currentTarget as HTMLSelectElement).value as FriendshipLevel)}><option value="good">Good Friend</option><option value="great">Great Friend</option><option value="ultra">Ultra Friend</option><option value="best">Best Friend</option></select></Field><Field label="Trade category"><select value={pokemonClass} onChange={(event) => setPokemonClass((event.currentTarget as HTMLSelectElement).value as TradePokemonClass)}><option value="standard-registered">Standard · both registered</option><option value="special-registered">Legendary/Shiny · registered</option><option value="standard-unregistered">Standard · unregistered</option><option value="special-unregistered">Legendary/Shiny · unregistered</option></select></Field><Field label="Catch distance" hint="km"><input type="number" min="0" value={distance} onInput={(event) => setDistance(Number((event.currentTarget as HTMLInputElement).value))}/></Field></div><div class="primary-result primary-result--blue"><span>Estimated Stardust cost</span><strong>{number(result.stardust)} <small>Stardust</small></strong><p>{result.candy} Candy earned from the reviewed catch-distance band</p></div><div class="secondary-result-grid"><ResultMetric label="Candy earned" value={result.candy}/><ResultMetric label="Guaranteed Candy XL" value={result.guaranteedCandyXl ? 'Distance condition met' : 'No'} tone={result.guaranteedCandyXl ? 'good' : 'default'}/><ResultMetric label="Special trade" value={result.specialTrade ? 'Yes' : 'No'}/></div><p class="assumption-note"><a href={pokemonGoTradeRules.sourceUrl} target="_blank" rel="noreferrer">{pokemonGoTradeRules.source}</a> · reviewed {pokemonGoTradeRules.reviewed}. {result.xlNote} Event bonuses and account-specific restrictions can override the standard table, so confirm the in-game confirmation screen before accepting.</p></div>;
}

function DpsCalculator() {
  const ids = useMemo(() => new Set(Object.keys(pokemonMovePools)), []); const [speciesId, setSpeciesId] = useState(ids.has('1-normal') ? '1-normal' : [...ids][0]); const [mode, setMode] = useState<'pve' | 'pvp'>('pve'); const [level, setLevel] = useState(40); const [attackIv, setAttackIv] = useState(15); const [targetDefense, setTargetDefense] = useState(150);
  const pool = pokemonMovePools[speciesId] ?? { fast: [], charged: [], eliteFast: [], eliteCharged: [] }; const fastRecords = mode === 'pve' ? pveFastMoves : pvpFastMoves; const chargedRecords = mode === 'pve' ? pveChargedMoves : pvpChargedMoves; const [fastName, setFastName] = useState(pool.fast[0] ?? 'Tackle'); const [chargedName, setChargedName] = useState(pool.charged[0] ?? 'Struggle');
  useEffect(() => { const next = pokemonMovePools[speciesId]; setFastName(next?.fast[0] ?? 'Tackle'); setChargedName(next?.charged[0] ?? 'Struggle'); }, [speciesId, mode]);
  const species = speciesOrDefault(speciesId); const stats = calculatePokemonStats(species, level, { attack: attackIv, defense: 15, stamina: 15 }); const findMove = (records: PokemonMove[], name: string) => records.find((move) => move.name === name) ?? records[0]; const fast = findMove(fastRecords, fastName); const charged = findMove(chargedRecords, chargedName); const result = calculateMoveDps(fast, charged, mode, stats.effectiveAttack, targetDefense);
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Neutral-target cycle model</span><h2>Compare a fast and charged move cycle</h2></div></div><Segmented label="Battle mode" value={mode} options={[{ value: 'pve', label: 'Raids & Gyms (PvE)' }, { value: 'pvp', label: 'Trainer Battles (PvP)' }]} onChange={setMode}/><div class="secondary-input-grid"><PokemonPicker value={speciesId} onChange={setSpeciesId} ids={ids}/><LevelPicker value={level} onChange={setLevel}/><Field label="Fast Move"><select value={fastName} onChange={(event) => setFastName((event.currentTarget as HTMLSelectElement).value)}>{pool.fast.map((name) => <option value={name}>{name}</option>)}</select></Field><Field label="Charged Move"><select value={chargedName} onChange={(event) => setChargedName((event.currentTarget as HTMLSelectElement).value)}>{pool.charged.map((name) => <option value={name}>{name}</option>)}</select></Field><Field label="Attack IV" hint="0–15"><input type="number" min="0" max="15" value={attackIv} onInput={(event) => setAttackIv(Number((event.currentTarget as HTMLInputElement).value))}/></Field><Field label="Target Defense"><input type="number" min="1" value={targetDefense} onInput={(event) => setTargetDefense(Number((event.currentTarget as HTMLInputElement).value))}/></Field></div><div class="primary-result primary-result--blue"><span>Estimated combined cycle DPS</span><strong>{result.cycleDps.toFixed(2)} <small>DPS</small></strong><p>{result.fastCount} × {fast.name} to fund one {charged.name}</p></div><div class="secondary-result-grid"><ResultMetric label="Fast Move DPS" value={result.fastDps.toFixed(2)}/><ResultMetric label="Charged Move DPS" value={result.chargedDps.toFixed(2)}/><ResultMetric label="Cycle time" value={`${result.cycleSeconds.toFixed(1)} s`}/><ResultMetric label="Fast energy gained" value={result.fastEnergy}/><ResultMetric label="Charged energy used" value={result.chargedEnergy}/><ResultMetric label="Effective Attack" value={formatStat(stats.effectiveAttack)}/></div><p class="assumption-note"><a href={moveMeta.sourceUrl} target="_blank" rel="noreferrer">{moveMeta.source}</a> · reviewed {moveMeta.reviewed}. The neutral-target model does not apply type effectiveness, STAB, weather, friendship, dodging, PvP shields, buffs, debuffs, or raid-party effects. PvE and PvP move records are never mixed.</p></div>;
}

function XpCalculator() {
  const [currentLevel, setCurrentLevel] = useState(1); const [totalXp, setTotalXp] = useState(0); const [targetLevel, setTargetLevel] = useState(40); const [xpPerAction, setXpPerAction] = useState(1_000); const detected = trainerLevelFromXp(totalXp); const actualCurrent = Math.max(currentLevel, detected); const safeTarget = Math.max(actualCurrent, targetLevel); const result = calculateTrainerXp(actualCurrent, totalXp, safeTarget); const actions = xpPerAction > 0 ? Math.ceil(result.xpRemaining / xpPerAction) : 0;
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Current Game Master XP table</span><h2>Plan Trainer-level progress</h2></div><span class="reference-count">Level {detected} by XP</span></div><div class="secondary-input-grid"><Field label="Current Trainer level"><select value={currentLevel} onChange={(event) => setCurrentLevel(Number((event.currentTarget as HTMLSelectElement).value))}>{[...trainerXpByLevel.keys()].map((level) => <option value={level}>{level}</option>)}</select></Field><Field label="Current total XP"><input type="number" min="0" value={totalXp} onInput={(event) => setTotalXp(Number((event.currentTarget as HTMLInputElement).value))}/></Field><Field label="Target Trainer level"><select value={targetLevel} onChange={(event) => setTargetLevel(Number((event.currentTarget as HTMLSelectElement).value))}>{[...trainerXpByLevel.keys()].filter((level) => level >= actualCurrent).map((level) => <option value={level}>{level}</option>)}</select></Field><Field label="Optional XP per action"><input type="number" min="1" value={xpPerAction} onInput={(event) => setXpPerAction(Number((event.currentTarget as HTMLInputElement).value))}/></Field></div><div class="primary-result primary-result--blue"><span>XP remaining</span><strong>{number(result.xpRemaining)} <small>XP</small></strong><div class="progress-track"><i style={{ width: `${result.percentComplete}%` }}></i></div><p>{result.levelsRemaining} Trainer levels · about {number(actions)} actions at your entered rate</p></div><div class="secondary-result-grid"><ResultMetric label="Current total XP" value={number(result.totalCurrentXp)}/><ResultMetric label="Target XP" value={number(result.targetXp)}/><ResultMetric label="Percentage complete" value={`${result.percentComplete.toFixed(1)}%`}/><ResultMetric label="Maximum table level" value={maxTrainerLevel}/></div><p class="assumption-note"><a href={trainerXpMeta.sourceUrl} target="_blank" rel="noreferrer">{trainerXpMeta.source}</a> · reviewed {trainerXpMeta.reviewed}. The action estimate uses only the XP-per-action number you supply; event multipliers and changing reward tables are not assumed.</p></div>;
}

export default function Calculator({ toolSlug }: Props) {
  if (toolSlug === 'cp-calculator') return <CpCalculator/>;
  if (toolSlug === 'evolution-calculator') return <EvolutionCalculator/>;
  if (toolSlug === 'stats-calculator') return <StatsCalculator/>;
  if (toolSlug === 'pvp-iv-calculator') return <PvpCalculator/>;
  if (toolSlug === 'purify-calculator') return <PurifyCalculator/>;
  if (toolSlug === 'power-up-calculator') return <PowerUpCalculator/>;
  if (toolSlug === 'trade-calculator') return <TradeCalculator/>;
  if (toolSlug === 'dps-calculator') return <DpsCalculator/>;
  return <XpCalculator/>;
}
