import { useEffect, useMemo, useState } from 'preact/hooks';
import { shareResult } from '../../../components/tools/CalculatorUi';
import { bloxFruits } from '../../../data/blox-fruits/items';
import { gardenItems } from '../../../data/grow-a-garden/items';
import type { SelectedValueItem, ValueItem } from '../../../data/types';
import { formatCompact } from '../../../utils/format';
import { calculateTrade } from './calculate';

function Offer({ title, items, catalog, onAdd, onRemove }: { title: string; items: SelectedValueItem[]; catalog: ValueItem[]; onAdd: (item: ValueItem) => void; onRemove: (slug: string) => void }) {
  const [choice, setChoice] = useState(catalog[0]?.slug ?? '');
  return <section class="offer-panel"><div class="offer-heading"><div><span>{title}</span><strong>{items.length} / 4 items</strong></div></div><div class="item-picker"><label class="sr-only">Choose an item</label><select value={choice} onChange={(event) => setChoice((event.target as HTMLSelectElement).value)}>{catalog.map((item) => <option value={item.slug}>{item.name}</option>)}</select><button type="button" onClick={() => { const item = catalog.find((candidate) => candidate.slug === choice); if (item) onAdd(item); }} disabled={items.length >= 4}>+ Add</button></div><div class="offer-items">{items.length ? items.map((item) => <div class="offer-item"><span class="item-orb">{item.name.slice(0, 2).toUpperCase()}</span><span><strong>{item.name}</strong><small>{item.rarity}{item.demand > 0 ? ` · Demand ${item.demand.toFixed(1)}` : ` · ${item.unit ?? 'reference'}`}</small></span><b>{formatCompact(item.value)}</b><button type="button" onClick={() => onRemove(item.slug)} aria-label={`Remove ${item.name}`}>×</button></div>) : <div class="empty-state"><span>＋</span><strong>Add your first item</strong><small>Choose from the reviewed reference list.</small></div>}</div><div class="offer-total"><span>Total reference</span><strong>{formatCompact(items.reduce((sum, item) => sum + item.value * item.quantity, 0))}</strong></div></section>;
}

export default function Calculator({ gameSlug }: { gameSlug: 'blox-fruits' | 'grow-a-garden' }) {
  const catalog = gameSlug === 'blox-fruits' ? bloxFruits : gardenItems;
  const label = gameSlug === 'blox-fruits' ? 'Blox Fruits' : 'Grow a Garden';
  const [yours, setYours] = useState<SelectedValueItem[]>([]);
  const [theirs, setTheirs] = useState<SelectedValueItem[]>([]);
  useEffect(() => { const params = new URLSearchParams(location.search); const parse = (value: string | null) => value?.split(',').map((slug) => catalog.find((item) => item.slug === slug)).filter((item): item is ValueItem => Boolean(item)).map((item) => ({ ...item, quantity: 1 })) ?? []; setYours(parse(params.get('give'))); setTheirs(parse(params.get('get'))); }, []);
  useEffect(() => { const params = new URLSearchParams(); if (yours.length) params.set('give', yours.map((item) => item.slug).join(',')); if (theirs.length) params.set('get', theirs.map((item) => item.slug).join(',')); history.replaceState({}, '', `${location.pathname}${params.size ? `?${params}` : ''}`); }, [yours, theirs]);
  const result = useMemo(() => calculateTrade(yours, theirs), [yours, theirs]);
  const add = (setter: typeof setYours, current: SelectedValueItem[], item: ValueItem) => { if (current.length < 4) setter([...current, { ...item, quantity: 1 }]); };
  const metricName = gameSlug === 'blox-fruits' ? 'dealer Beli price' : 'base Sheckle value';
  return <div class="calculator trade-calculator"><div class="calculator-header"><div><span class="eyebrow">Multi-item baseline comparison</span><h2>Build both sides</h2></div><button class="text-button" type="button" onClick={() => { setYours([]); setTheirs([]); }}>Clear all</button></div><div class="trade-grid"><Offer title="Your offer" items={yours} catalog={catalog} onAdd={(item) => add(setYours, yours, item)} onRemove={(slug) => setYours(yours.filter((item) => item.slug !== slug))}/><button class="swap-button" type="button" onClick={() => { setYours(theirs); setTheirs(yours); }} aria-label="Swap trade sides">⇄</button><Offer title="Their offer" items={theirs} catalog={catalog} onAdd={(item) => add(setTheirs, theirs, item)} onRemove={(slug) => setTheirs(theirs.filter((item) => item.slug !== slug))}/></div><div class={`trade-result verdict-${result.verdict.toLowerCase()}`}><div><span>Baseline result</span><strong>{result.verdict}</strong><small>{result.verdict === 'Good' ? 'Their side has more reference value' : result.verdict === 'Fair' ? 'Baselines are within the comparison band' : 'Your side has more reference value'}</small></div><div class="comparison"><span><small>Your offer</small><strong>{formatCompact(result.yourTotal)}</strong></span><i><b style={{ width: `${result.yourTotal + result.theirTotal ? result.yourTotal / (result.yourTotal + result.theirTotal) * 100 : 50}%` }}></b></i><span><small>Their offer</small><strong>{formatCompact(result.theirTotal)}</strong></span></div><div class="trade-difference"><span>Difference <strong>{result.difference >= 0 ? '+' : ''}{formatCompact(result.difference)}</strong></span><span>Value gap <strong>{result.percentage >= 0 ? '+' : ''}{result.percentage.toFixed(1)}%</strong></span><span>Metric <strong>{metricName}</strong></span></div></div><div class="calculator-actions"><button class="button button--primary" type="button" disabled={!yours.length && !theirs.length} onClick={() => shareResult(`${label} baseline comparison`, `${result.verdict}: ${formatCompact(result.yourTotal)} vs ${formatCompact(result.theirTotal)} (${result.percentage.toFixed(1)}% gap).`)}>Share result</button><button class="button button--secondary" type="button" onClick={() => navigator.clipboard.writeText(location.href)}>Copy comparison link</button></div><p class="assumption-note">This compares {metricName}, not a live player-market price. The datasets are dated and sourced; mutations, demand and player preference may make a real trade differ.</p></div>;
}
