import { useMemo, useState } from 'preact/hooks';
import { ResultMetric, shareResult } from '../../../components/tools/CalculatorUi';
import { adoptMePets } from '../../../data/adopt-me/pets';
import { formatNumber } from '../../../utils/format';
import { calculatePetCollection, type PetSelection, type PetVariant } from './calculate';

export default function Calculator({ mode = 'value' }: { mode?: 'value' | 'pet' }) {
  const [selections, setSelections] = useState<PetSelection[]>([{ pet: adoptMePets[0], quantity: 1, variant: 'regular', fly: false, ride: false }]);
  const [choice, setChoice] = useState(adoptMePets[1].slug);
  const result = useMemo(() => calculatePetCollection(selections), [selections]);
  return <div class="calculator">
    <div class="calculator-header"><div><span class="eyebrow">{mode === 'pet' ? 'Pet variant comparison' : 'Community-index inventory'}</span><h2>{mode === 'pet' ? 'Compare pet variants' : 'Total your pets'}</h2></div><button class="text-button" type="button" onClick={() => setSelections([])}>Clear</button></div>
    <div class="item-picker item-picker--large"><select value={choice} onChange={(event) => setChoice((event.target as HTMLSelectElement).value)}>{adoptMePets.map((pet) => <option value={pet.slug}>{pet.name} · {pet.value} index</option>)}</select><button type="button" onClick={() => { const pet = adoptMePets.find((entry) => entry.slug === choice); if (pet && !selections.some((entry) => entry.pet.slug === choice)) setSelections([...selections, { pet, quantity: 1, variant: 'regular', fly: false, ride: false }]); }}>+ Add pet</button></div>
    <div class="pet-list">{selections.length ? selections.map((selection) => <div class="pet-row"><span class="item-orb">{selection.pet.name.slice(0, 2).toUpperCase()}</span><span class="pet-name"><strong>{selection.pet.name}</strong><small>{selection.pet.value} regular community index</small></span><label><small>Variant</small><select value={selection.variant} onChange={(event) => setSelections(selections.map((entry) => entry.pet.slug === selection.pet.slug ? { ...entry, variant: (event.target as HTMLSelectElement).value as PetVariant } : entry))}><option value="regular">Regular</option><option value="neon">Neon estimate</option><option value="mega">Mega estimate</option></select></label><label class="mini-check"><input type="checkbox" checked={selection.fly} onChange={(event) => setSelections(selections.map((entry) => entry.pet.slug === selection.pet.slug ? { ...entry, fly: (event.target as HTMLInputElement).checked } : entry))}/> Fly estimate</label><label class="mini-check"><input type="checkbox" checked={selection.ride} onChange={(event) => setSelections(selections.map((entry) => entry.pet.slug === selection.pet.slug ? { ...entry, ride: (event.target as HTMLInputElement).checked } : entry))}/> Ride estimate</label><input aria-label={`${selection.pet.name} quantity`} type="number" min="1" max="99" value={selection.quantity} onInput={(event) => setSelections(selections.map((entry) => entry.pet.slug === selection.pet.slug ? { ...entry, quantity: Number((event.target as HTMLInputElement).value) } : entry))}/><button type="button" onClick={() => setSelections(selections.filter((entry) => entry.pet.slug !== selection.pet.slug))}>×</button></div>) : <div class="empty-state"><span>＋</span><strong>No pets added</strong><small>Add pets to calculate a total.</small></div>}</div>
    <div class="primary-result primary-result--coral"><span>Total normalized value</span><strong>{formatNumber(result.total)} <small>community-index points</small></strong><p>Use this to compare relative value, not as an official Adopt Me price.</p></div>
    <div class="result-grid"><ResultMetric label="Pets added" value={selections.length}/><ResultMetric label="Dataset size" value={adoptMePets.length}/></div>
    <div class="calculator-actions"><button class="button button--primary" type="button" onClick={() => shareResult('Adopt Me pet value', `My pets total ${formatNumber(result.total)} community-index points.`)}>Share result</button></div>
    <p class="assumption-note"><a href={adoptMePets[0].sourceUrl} target="_blank" rel="noreferrer">AdoptMe.rocks</a> is a fan-made daily value index, not an official Adopt Me list. Reviewed {adoptMePets[0].updated}. Neon, Mega, Fly and Ride adjustments are transparent planning estimates and may not match a specific live offer.</p>
  </div>;
}
