import { useEffect, useMemo, useState } from 'preact/hooks';
import { Field, ResultMetric } from '../../components/tools/CalculatorUi';
import { palPassives, passiveInheritanceMeta } from '../../data/palworld/passive-skills';
import { palsById, regularBreedingPals, statPals } from '../../data/palworld/pals';
import { palStatMeta } from '../../data/palworld/stat-scaling';
import { palworldMutationRules } from '../../data/palworld/mutation';
import { palWorkMeta, workSuitabilitySpeeds } from '../../data/palworld/work-speed';
import type { Pal } from '../../data/palworld/types';
import { calculateBreeding, calculateMutation, calculatePalStats, calculatePassiveInheritance, calculateWorkSpeed, potentialRange, reverseBreeding, type PalStatInput } from './calculate';
import BreedingCalculator from './breeding-calculator/Calculator';
import { PalPicker } from './ui';

type Props = { toolSlug: string; toolName: string };
const fmt = (value: number, digits = 0) => value.toLocaleString(undefined, { maximumFractionDigits: digits });
const defaultPal = () => statPals.find((pal) => pal.name === 'Lamball') ?? statPals[0];

const neutralModifiers = { hpBonusPercent: 0, attackBonusPercent: 0, defenseBonusPercent: 0, soulHpPercent: 0, soulAttackPercent: 0, soulDefensePercent: 0, condensationStars: 0 };
function ModifierFields({ values, update }: { values: Omit<PalStatInput, 'level' | 'hpPotential' | 'attackPotential' | 'defensePotential'>; update: (value: typeof values) => void }) {
  const field = (key: keyof typeof values, label: string, max = 200) => <Field label={label} hint={key === 'condensationStars' ? '0–4' : '%'}><input type="number" min="0" max={max} value={values[key]} onInput={(event) => update({ ...values, [key]: Number((event.currentTarget as HTMLInputElement).value) })}/></Field>;
  return <>{field('hpBonusPercent', 'HP passive bonus')}{field('attackBonusPercent', 'Attack passive bonus')}{field('defenseBonusPercent', 'Defense passive bonus')}{field('soulHpPercent', 'HP Soul bonus')}{field('soulAttackPercent', 'Attack Soul bonus')}{field('soulDefensePercent', 'Defense Soul bonus')}{field('condensationStars', 'Condensation stars', 4)}</>;
}

function IvCalculator() {
  const [palId, setPalId] = useState(defaultPal().id); const [level, setLevel] = useState(10); const [displayed, setDisplayed] = useState({ hp: 900, attack: 180, defense: 100 }); const [modifiers, setModifiers] = useState(neutralModifiers); const pal = palsById.get(palId) ?? defaultPal();
  useEffect(() => { const stats = calculatePalStats(pal, { level, hpPotential: 50, attackPotential: 50, defensePotential: 50, ...modifiers }); setDisplayed({ hp: stats.hp, attack: stats.attack, defense: stats.defense }); }, [palId]);
  const ranges = useMemo(() => potentialRange(pal, displayed, { level, ...modifiers }), [pal, displayed, level, modifiers]); const quality = (minimum: number, maximum: number) => maximum >= 80 ? minimum >= 80 ? 'Excellent' : 'Could be excellent' : maximum >= 50 ? 'Average range' : 'Below average';
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Potential range from rounded stats</span><h2>Estimate Palworld IV / Potential</h2></div></div><div class="secondary-input-grid"><PalPicker value={palId} onChange={setPalId} statsOnly/><Field label="Pal level"><input type="number" min="1" max="100" value={level} onInput={(event) => setLevel(Number((event.currentTarget as HTMLInputElement).value))}/></Field><Field label="Displayed HP"><input type="number" min="1" value={displayed.hp} onInput={(event) => setDisplayed({ ...displayed, hp: Number((event.currentTarget as HTMLInputElement).value) })}/></Field><Field label="Displayed Attack"><input type="number" min="1" value={displayed.attack} onInput={(event) => setDisplayed({ ...displayed, attack: Number((event.currentTarget as HTMLInputElement).value) })}/></Field><Field label="Displayed Defense"><input type="number" min="1" value={displayed.defense} onInput={(event) => setDisplayed({ ...displayed, defense: Number((event.currentTarget as HTMLInputElement).value) })}/></Field></div><details class="advanced-settings"><summary>Passive, Soul and Condensation bonuses <span>+</span></summary><div class="secondary-input-grid"><ModifierFields values={modifiers} update={setModifiers}/></div></details><div class="primary-result primary-result--blue"><span>Potential quality</span><strong>{quality(ranges.attack.minimum, ranges.attack.maximum)}</strong><p>Displayed stats are floored, so the truthful answer can contain several 0–100 Potential values.</p></div><div class="secondary-result-grid"><ResultMetric label="HP Potential range" value={`${ranges.hp.minimum}–${ranges.hp.maximum}`}/><ResultMetric label="Attack Potential range" value={`${ranges.attack.minimum}–${ranges.attack.maximum}`}/><ResultMetric label="Defense Potential range" value={`${ranges.defense.minimum}–${ranges.defense.maximum}`}/><ResultMetric label="All stats matched" value={ranges.hp.exactDisplayMatch && ranges.attack.exactDisplayMatch && ranges.defense.exactDisplayMatch ? 'Yes' : 'Nearest only'} tone={ranges.hp.exactDisplayMatch && ranges.attack.exactDisplayMatch && ranges.defense.exactDisplayMatch ? 'good' : 'warn'}/></div><p class="assumption-note"><a href={palStatMeta.sourceUrl} target="_blank" rel="noreferrer">{palStatMeta.source}</a> · reviewed {palStatMeta.reviewed}. Low-level Pals often return wider ranges because multiple Potential values floor to the same displayed integer. Alpha and exceptional boss HP rules require the correct record and modifiers.</p></div>;
}

function StatCalculator() {
  const [palId, setPalId] = useState(defaultPal().id); const [level, setLevel] = useState(50); const [potentials, setPotentials] = useState({ hpPotential: 50, attackPotential: 50, defensePotential: 50 }); const [modifiers, setModifiers] = useState(neutralModifiers); const pal = palsById.get(palId) ?? defaultPal(); const result = calculatePalStats(pal, { level, ...potentials, ...modifiers }); const perfect = calculatePalStats(pal, { level, hpPotential: 100, attackPotential: 100, defensePotential: 100, ...modifiers });
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Forward Potential calculation</span><h2>Project a Pal’s HP, Attack and Defense</h2></div></div><div class="secondary-input-grid"><PalPicker value={palId} onChange={setPalId} statsOnly/><Field label="Pal level"><input type="number" min="1" max="100" value={level} onInput={(event) => setLevel(Number((event.currentTarget as HTMLInputElement).value))}/></Field>{(['hpPotential', 'attackPotential', 'defensePotential'] as const).map((key) => <Field label={`${key.replace('Potential', '')} Potential`} hint="0–100"><input type="number" min="0" max="100" value={potentials[key]} onInput={(event) => setPotentials({ ...potentials, [key]: Number((event.currentTarget as HTMLInputElement).value) })}/></Field>)}</div><details class="advanced-settings"><summary>Stat modifiers <span>+</span></summary><div class="secondary-input-grid"><ModifierFields values={modifiers} update={setModifiers}/></div></details><div class="primary-result primary-result--blue"><span>Estimated combat stats</span><strong>{fmt(result.hp)} <small>HP</small></strong><p>{fmt(result.attack)} Attack · {fmt(result.defense)} Defense</p></div><div class="interactive-table-wrap"><table class="interactive-table"><thead><tr><th>Stat</th><th>Current Potential</th><th>100 Potential</th><th>Gap</th></tr></thead><tbody><tr><th>HP</th><td>{result.hp}</td><td>{perfect.hp}</td><td>{perfect.hp - result.hp}</td></tr><tr><th>Attack</th><td>{result.attack}</td><td>{perfect.attack}</td><td>{perfect.attack - result.attack}</td></tr><tr><th>Defense</th><td>{result.defense}</td><td>{perfect.defense}</td><td>{perfect.defense - result.defense}</td></tr></tbody></table></div><details class="advanced-settings" open><summary>Formula stages <span>+</span></summary><div class="formula-breakdown"><p>Species scaling produces floored base stages: {result.baseHpStage} HP, {result.baseAttackStage} Attack and {result.baseDefenseStage} Defense.</p><p>Passive, Soul and ×{result.condensationMultiplier.toFixed(2)} Condensation multipliers are applied before the final floor.</p></div></details><p class="assumption-note">Potential 100 multiplies the species level-scaling term by 1.30, not 2.00. The comparison preserves every other entered modifier.</p></div>;
}

function ReverseBreedingCalculator() {
  const [childId, setChildId] = useState(regularBreedingPals.find((pal) => pal.name === 'Anubis')?.id ?? regularBreedingPals[0].id); const [owned, setOwned] = useState<string[]>([]); const [ownedChoice, setOwnedChoice] = useState(regularBreedingPals[0].id); const [ownership, setOwnership] = useState<'all' | 'both' | 'one'>('all'); const [excludeLegendary, setExcludeLegendary] = useState(true); const [includeSpecial, setIncludeSpecial] = useState(true); const [maxRarity, setMaxRarity] = useState(20);
  useEffect(() => { try { setOwned(JSON.parse(localStorage.getItem('gc:palworld:owned') ?? '[]')); } catch { setOwned([]); } const requestedChild = new URLSearchParams(location.search).get('child'); if (requestedChild && regularBreedingPals.some((pal) => pal.id === requestedChild)) setChildId(requestedChild); }, []); useEffect(() => { localStorage.setItem('gc:palworld:owned', JSON.stringify(owned)); }, [owned]);
  const rows = useMemo(() => reverseBreeding(childId).filter((row) => includeSpecial || !row.special).filter((row) => !excludeLegendary || (row.parentA.rarity < 9 && row.parentB.rarity < 9)).filter((row) => row.parentA.rarity <= maxRarity && row.parentB.rarity <= maxRarity).filter((row) => { const count = Number(owned.includes(row.parentA.id)) + Number(owned.includes(row.parentB.id)); return ownership === 'all' || ownership === 'both' && count === 2 || ownership === 'one' && count >= 1; }).sort((a, b) => (Number(owned.includes(b.parentA.id)) + Number(owned.includes(b.parentB.id))) - (Number(owned.includes(a.parentA.id)) + Number(owned.includes(a.parentB.id)))), [childId, owned, ownership, excludeLegendary, includeSpecial, maxRarity]);
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Parent pairs for one child</span><h2>Reverse a Palworld breeding target</h2></div><span class="reference-count">{rows.length} combinations</span></div><div class="secondary-input-grid"><PalPicker value={childId} onChange={setChildId} label="Desired Child Pal"/><Field label="Owned-pair filter"><select value={ownership} onChange={(event) => setOwnership((event.currentTarget as HTMLSelectElement).value as typeof ownership)}><option value="all">Show all</option><option value="both">Both parents owned</option><option value="one">At least one owned</option></select></Field><Field label="Maximum parent rarity"><input type="number" min="1" max="20" value={maxRarity} onInput={(event) => setMaxRarity(Number((event.currentTarget as HTMLInputElement).value))}/></Field><label class="calc-field"><span>Parent filters</span><span><input type="checkbox" checked={excludeLegendary} onChange={() => setExcludeLegendary(!excludeLegendary)}/> Exclude high-rarity parents</span><span><input type="checkbox" checked={includeSpecial} onChange={() => setIncludeSpecial(!includeSpecial)}/> Include special combinations</span></label></div><details class="advanced-settings"><summary>Mark owned Pals on this device ({owned.length}) <span>+</span></summary><div class="code-entry"><PalPicker value={ownedChoice} onChange={setOwnedChoice}/><button class="button button--secondary" type="button" onClick={() => setOwned(owned.includes(ownedChoice) ? owned.filter((id) => id !== ownedChoice) : [...owned, ownedChoice])}>{owned.includes(ownedChoice) ? 'Remove owned' : 'Mark owned'}</button></div></details><div class="interactive-table-wrap"><table class="interactive-table"><thead><tr><th>Parent A</th><th>Parent B</th><th>Owned</th><th>Combination</th></tr></thead><tbody>{rows.slice(0, 250).map((row) => <tr><th>{row.parentA.name}</th><td>{row.parentB.name}</td><td>{Number(owned.includes(row.parentA.id)) + Number(owned.includes(row.parentB.id))}/2</td><td>{row.special ? 'Special override' : `Rank target ${row.targetRank}`}</td></tr>)}</tbody></table></div>{rows.length > 250 && <p class="assumption-note">Showing the first 250 owned-first matches. Tighten ownership or rarity filters to reduce the list.</p>}</div>;
}

function PassiveCalculator() {
  const defaultNames = ['Artisan', 'Serious', 'Work Slave', 'Lucky']; const [parentA, setParentA] = useState('Artisan, Serious'); const [parentB, setParentB] = useState('Work Slave, Lucky'); const [desired, setDesired] = useState(defaultNames.join(', ')); const parse = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean); const result = calculatePassiveInheritance([...parse(parentA), ...parse(parentB)], parse(desired));
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Unique passive-pool probability</span><h2>Estimate desired passive inheritance</h2></div></div><datalist id="pal-passives">{palPassives.map((passive) => <option value={passive.name}/>)}</datalist><div class="secondary-input-grid"><Field label="Parent A passives"><input value={parentA} placeholder="Comma-separated" onInput={(event) => setParentA((event.currentTarget as HTMLInputElement).value)}/></Field><Field label="Parent B passives"><input value={parentB} placeholder="Comma-separated" onInput={(event) => setParentB((event.currentTarget as HTMLInputElement).value)}/></Field><Field label="Desired child passives"><input value={desired} placeholder="Comma-separated" onInput={(event) => setDesired((event.currentTarget as HTMLInputElement).value)}/></Field></div><div class="primary-result primary-result--blue"><span>Chance all requested are inherited</span><strong>{(result.chanceAllDesired * 100).toFixed(2)}<small>%</small></strong><p>{(result.chanceAllWithoutRandom * 100).toFixed(2)}% baseline for all requested with no additional random passive</p></div><div class="secondary-result-grid"><ResultMetric label="Unique parent passives" value={result.uniqueParentPassives}/><ResultMetric label="Desired passives found" value={result.desiredAvailable}/><ResultMetric label="Additional random risk" value={`${(result.riskAdditionalRandom * 100).toFixed(0)}%`}/></div><details class="advanced-settings" open><summary>Reviewed inheritance weights <span>+</span></summary><div class="interactive-table-wrap"><table class="interactive-table"><thead><tr><th>Inherited count roll</th><th>Probability</th></tr></thead><tbody><tr><th>1</th><td>40%</td></tr><tr><th>2</th><td>30%</td></tr><tr><th>3</th><td>20%</td></tr><tr><th>4</th><td>10%</td></tr></tbody></table></div></details><p class="assumption-note"><a href={passiveInheritanceMeta.sourceUrl} target="_blank" rel="noreferrer">{passiveInheritanceMeta.source}</a> · reviewed {passiveInheritanceMeta.reviewed}. Duplicate passives are removed from the parent pool. The result models inherited passives and the documented no-random baseline; it does not count the small chance that a random roll independently produces a requested name.</p></div>;
}

function MutationCalculator() {
  const [eggs, setEggs] = useState(100); const [cake, setCake] = useState<'cake' | 'extravagant'>('cake'); const rule = palworldMutationRules.cakeRates.find((item) => item.id === cake)!; const result = calculateMutation(eggs, rule.probability);
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Independent mutation probability</span><h2>Plan a Palworld breeding egg batch</h2></div></div><div class="secondary-input-grid"><Field label="Number of eggs"><input type="number" min="0" max="100000" value={eggs} onInput={(event) => setEggs(Number((event.currentTarget as HTMLInputElement).value))}/></Field><Field label="Cake type"><select value={cake} onChange={(event) => setCake((event.currentTarget as HTMLSelectElement).value as typeof cake)}>{palworldMutationRules.cakeRates.map((item) => <option value={item.id}>{item.name} · {item.probability * 100}%</option>)}</select></Field></div><div class="primary-result primary-result--blue"><span>Chance of at least one mutated egg</span><strong>{(result.atLeastOne * 100).toFixed(3)}<small>%</small></strong><div class="progress-track"><i style={{ width: `${result.atLeastOne * 100}%` }}></i></div><p>{(result.zero * 100).toFixed(3)}% chance of zero mutations</p></div><div class="secondary-result-grid"><ResultMetric label="Mutation chance per egg" value={`${(result.perEgg * 100).toFixed(0)}%`}/><ResultMetric label="Expected mutated eggs" value={result.expected.toFixed(2)}/><ResultMetric label="Eggs evaluated" value={fmt(result.eggs)}/></div><p class="assumption-note"><a href={palworldMutationRules.sourceUrl} target="_blank" rel="noreferrer">{palworldMutationRules.source}</a> · reviewed {palworldMutationRules.reviewed}. At least one equals 1 − (1 − p)ⁿ. Expected count is a long-run average, not a guaranteed outcome for the batch.</p></div>;
}

type WorkSetup = { baseWorkSpeed: number; passivePercent: number; foodPercent: number; soulPercent: number; buildingPercent: number; workload: number };
function WorkSpeedCalculator() {
  const [palId, setPalId] = useState(regularBreedingPals[0].id); const [job, setJob] = useState<'general' | 'handiwork'>('general'); const [level, setLevel] = useState(2); const defaultSpeed = workSuitabilitySpeeds.general.find((row) => row.level === 2)!.speed; const [a, setA] = useState<WorkSetup>({ baseWorkSpeed: defaultSpeed, passivePercent: 50, foodPercent: 0, soulPercent: 0, buildingPercent: 0, workload: 1_000 }); const [b, setB] = useState<WorkSetup>({ baseWorkSpeed: defaultSpeed, passivePercent: 100, foodPercent: 20, soulPercent: 0, buildingPercent: 0, workload: 1_000 }); const resultA = calculateWorkSpeed(a); const resultB = calculateWorkSpeed(b);
  const chooseLevel = (value: number) => { setLevel(value); const speed = workSuitabilitySpeeds[job].find((row) => row.level === value)?.speed ?? 70; setA({ ...a, baseWorkSpeed: speed }); setB({ ...b, baseWorkSpeed: speed }); };
  const editor = (label: string, value: WorkSetup, update: (value: WorkSetup) => void) => <section class="gear-setup"><h3>{label}</h3>{([['baseWorkSpeed', 'Base Work Speed'], ['passivePercent', 'Passive bonus %'], ['foodPercent', 'Food bonus %'], ['soulPercent', 'Soul bonus %'], ['buildingPercent', 'Building bonus %'], ['workload', 'Workload']] as const).map(([key, fieldLabel]) => <Field label={fieldLabel}><input type="number" min="0" value={value[key]} onInput={(event) => update({ ...value, [key]: Number((event.currentTarget as HTMLInputElement).value) })}/></Field>)}</section>;
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Workload ÷ Work Speed</span><h2>Compare two Pal work setups</h2></div><button class="text-button" type="button" onClick={() => { setA(b); setB(a); }}>Swap</button></div><div class="secondary-input-grid"><PalPicker value={palId} onChange={setPalId}/><Field label="Work category"><select value={job} onChange={(event) => { const nextJob = (event.currentTarget as HTMLSelectElement).value as typeof job; setJob(nextJob); const row = workSuitabilitySpeeds[nextJob].find((item) => item.level === level) ?? workSuitabilitySpeeds[nextJob][0]; setA((current) => ({ ...current, baseWorkSpeed: row.speed })); setB((current) => ({ ...current, baseWorkSpeed: row.speed })); }}><option value="general">Mining / Lumbering / Planting / Watering</option><option value="handiwork">Handiwork / Kindling / Medicine</option></select></Field><Field label="Work suitability level"><select value={level} onChange={(event) => chooseLevel(Number((event.currentTarget as HTMLSelectElement).value))}>{workSuitabilitySpeeds[job].map((row) => <option value={row.level}>Level {row.level} · {row.speed} base speed</option>)}</select></Field></div><div class="gear-compare-grid">{editor('Setup A', a, setA)}{editor('Setup B', b, setB)}</div><div class="primary-result primary-result--blue"><span>Faster setup</span><strong>{resultA.seconds <= resultB.seconds ? 'Setup A' : 'Setup B'}</strong><p>{Math.abs(resultA.seconds - resultB.seconds)} seconds difference for the entered workload</p></div><div class="interactive-table-wrap"><table class="interactive-table"><thead><tr><th>Output</th><th>Setup A</th><th>Setup B</th></tr></thead><tbody><tr><th>Effective Work Speed</th><td>{fmt(resultA.effectiveWorkSpeed, 2)}</td><td>{fmt(resultB.effectiveWorkSpeed, 2)}</td></tr><tr><th>Work / second</th><td>{fmt(resultA.workPerSecond, 2)}</td><td>{fmt(resultB.workPerSecond, 2)}</td></tr><tr><th>Completion time</th><td>{resultA.seconds}s</td><td>{resultB.seconds}s</td></tr><tr><th>Time saved vs base</th><td>{resultA.timeSaved}s</td><td>{resultB.timeSaved}s</td></tr></tbody></table></div><p class="assumption-note"><a href={palWorkMeta.sourceUrl} target="_blank" rel="noreferrer">{palWorkMeta.source}</a> · reviewed {palWorkMeta.reviewed}. Transporting, Cooling, Electricity and Ranch output do not use this generic completion-time interpretation.</p></div>;
}

function BreedingCombos() {
  const [query, setQuery] = useState(''); const [specialOnly, setSpecialOnly] = useState(true); const all = useMemo(() => { const rows: { parentA: Pal; parentB: Pal; child: Pal; special: boolean }[] = []; for (let a = 0; a < regularBreedingPals.length; a += 1) for (let b = a; b < regularBreedingPals.length; b += 1) { const result = calculateBreeding(regularBreedingPals[a], regularBreedingPals[b]); rows.push({ parentA: regularBreedingPals[a], parentB: regularBreedingPals[b], child: result.child, special: result.special }); } return rows; }, []); const filtered = all.filter((row) => !specialOnly || row.special).filter((row) => `${row.parentA.name} ${row.parentB.name} ${row.child.name}`.toLowerCase().includes(query.toLowerCase()));
  return <div class="calculator universal-tool"><div class="calculator-header"><div><span class="eyebrow">Searchable local breeding reference</span><h2>Explore parent and child combinations</h2></div><span class="reference-count">{fmt(filtered.length)} matches</span></div><div class="reference-controls"><Field label="Search parent or child"><input type="search" value={query} onInput={(event) => setQuery((event.currentTarget as HTMLInputElement).value)}/></Field><Field label="Combination type"><select value={specialOnly ? 'special' : 'all'} onChange={(event) => setSpecialOnly((event.currentTarget as HTMLSelectElement).value === 'special')}><option value="special">Special only</option><option value="all">All calculated</option></select></Field></div><div class="interactive-table-wrap"><table class="interactive-table"><thead><tr><th>Parent A</th><th>Parent B</th><th>Child</th><th>Type</th><th>Reviewed</th><th>Open</th></tr></thead><tbody>{filtered.slice(0, 500).map((row) => <tr><th>{row.parentA.name}</th><td>{row.parentB.name}</td><td>{row.child.name}</td><td>{row.special ? 'Special combination' : 'Rank-based result'}</td><td>2026-09-05</td><td><a href={`/palworld/breeding-calculator/?parentA=${encodeURIComponent(row.parentA.id)}&parentB=${encodeURIComponent(row.parentB.id)}`}>Parents</a> · <a href={`/palworld/reverse-breeding-calculator/?child=${encodeURIComponent(row.child.id)}`}>Child</a></td></tr>)}</tbody></table></div>{filtered.length > 500 && <p class="assumption-note">Showing 500 of {fmt(filtered.length)} calculated rows. Search a Pal name or select Special only to narrow the reference.</p>}<div class="calculator-actions"><a class="button button--primary" href="/palworld/breeding-calculator/">Open Breeding Calculator</a><a class="button button--secondary" href="/palworld/reverse-breeding-calculator/">Open Reverse Breeding</a></div></div>;
}

export default function Calculator({ toolSlug }: Props) {
  if (toolSlug === 'breeding-calculator') return <BreedingCalculator/>;
  if (toolSlug === 'iv-calculator') return <IvCalculator/>;
  if (toolSlug === 'reverse-breeding-calculator') return <ReverseBreedingCalculator/>;
  if (toolSlug === 'passive-inheritance-calculator') return <PassiveCalculator/>;
  if (toolSlug === 'mutation-calculator') return <MutationCalculator/>;
  if (toolSlug === 'stat-calculator') return <StatCalculator/>;
  if (toolSlug === 'work-speed-calculator') return <WorkSpeedCalculator/>;
  return <BreedingCombos/>;
}
